import { FocusMonitor } from '@angular/cdk/a11y';
import { CdkConnectedOverlay, CdkOverlayOrigin, ConnectedOverlayPositionChange } from '@angular/cdk/overlay';
import { Platform } from '@angular/cdk/platform';
import { AfterContentInit, AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, OnDestroy, OnInit, Renderer2, TemplateRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { NzNoAnimationDirective, NzSizeLDSType } from 'ng-zorro-antd/core';
import { DropdownPanelService } from './dropdown-panel.service';
import { PanelSelectTopControlComponent } from './p-panel-top-control.component';
import { POption } from './interface';
export declare class DropdownPanelComponent implements ControlValueAccessor, OnInit, AfterViewInit, OnDestroy, AfterContentInit {
    private renderer;
    dropdownPanelService: DropdownPanelService;
    private cdr;
    private focusMonitor;
    private platform;
    noAnimation?: NzNoAnimationDirective | undefined;
    _open: boolean;
    value: any | any[];
    dropDownPosition: 'top' | 'center' | 'bottom';
    triggerWidth: number;
    private _data;
    private _disabled;
    private _autoFocus;
    private isInit;
    private destroy$;
    cdkOverlayOrigin: CdkOverlayOrigin;
    cdkConnectedOverlay: CdkConnectedOverlay;
    panelTopControlComponent: PanelSelectTopControlComponent;
    /** should move to nz-option-container when https://github.com/angular/angular/issues/20810 resolved **/
    readonly onSearch: EventEmitter<string>;
    readonly scrollToBottom: EventEmitter<void>;
    readonly openChange: EventEmitter<boolean>;
    readonly pBlur: EventEmitter<void>;
    readonly pFocus: EventEmitter<void>;
    size: NzSizeLDSType;
    dropdownClassName: string;
    dropdownMatchSelectWidth: boolean;
    dropdownStyle: {
        [key: string]: string;
    };
    notFoundContent: string;
    allowClear: boolean;
    showSearch: boolean;
    loading: boolean;
    placeHolder: string;
    maxTagCount: number;
    suffixIcon: TemplateRef<void>;
    clearIcon: TemplateRef<void>;
    removeIcon: TemplateRef<void>;
    menuItemSelectedIcon: TemplateRef<void>;
    showArrow: boolean;
    data: POption[];
    autoClearSearchValue: boolean;
    maxMultipleCount: number;
    serverSearch: boolean;
    mode: 'default' | 'multiple' | 'tags';
    filterOption: any;
    compareWith: (o1: any, o2: any) => boolean;
    autoFocus: boolean;
    open: boolean;
    disabled: boolean;
    onChange: (value: string | string[]) => void;
    onTouched: () => void;
    updateAutoFocus(): void;
    focus(): void;
    blur(): void;
    onKeyDown(event: KeyboardEvent): void;
    toggleDropDown(): void;
    closeDropDown(): void;
    onPositionChange(position: ConnectedOverlayPositionChange): void;
    updateCdkConnectedOverlayStatus(): void;
    updateCdkConnectedOverlayPositions(): void;
    constructor(renderer: Renderer2, dropdownPanelService: DropdownPanelService, cdr: ChangeDetectorRef, focusMonitor: FocusMonitor, platform: Platform, elementRef: ElementRef, noAnimation?: NzNoAnimationDirective | undefined);
    /** update ngModel -> update listOfSelectedValue */
    writeValue(value: any | any[]): void;
    registerOnChange(fn: (value: string | string[]) => void): void;
    registerOnTouched(fn: () => void): void;
    setDisabledState(isDisabled: boolean): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngAfterContentInit(): void;
    ngOnDestroy(): void;
}
